name: "pagely-deploy-staging"
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    name: Deploy to Sandhills Development - Staging
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run deploy
        uses: pagely/action-deploy@v1
        with:
          PAGELY_DEPLOY_DEST: "/httpdocs/wp-content/themes/sandhills-site"
          PAGELY_INTEGRATION_SECRET: ${{secrets.PAGELY_INTEGRATION_SECRET}}
          PAGELY_INTEGRATION_ID: "NCPKntTcDJRQMfEQyRo268"
          PAGELY_APP_ID: "31999"
          PAGELY_WORKING_DIR: ${{github.workspace}}